config-version: 2

name: "jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.5.0"


profile: emap # Put your profile here

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "target-base"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"

flags:
  require_yaml_configuration_for_mf_time_spines: False

models:
  jaffle_shop:
    +materialized: table
    +schema: '123456789'

tests:
  jaffle_shop:
    +store_failures: true
    +schema: '123456789'