default:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: emap-summer-2025
      dataset: matricula_dev
      location: us-central1
      threads: 10
      keyfile: /path/to/emap-summer-2025-matricula.json
    prod:
      type: bigquery
      method: service-account
      project: emap-summer-2025
      dataset: matricula_prod
      location: us-central1
      threads: 10
      keyfile: /path/to/emap-summer-2025-matricula.json
